# Generated by Django 2.2.1 on 2019-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
